#define TS_ENERGY_ACCURACY 1d-6
#define TS_FORCES_ACCURACY 1d-7
#define TS_NUM_GRAD_DELTA 1d-3
#define N_FREQUENCY_GRID 15
#define K_GRID_SHIFT 0.5d0
#define TS_DAMPING_D 20d0
#define MBD_DAMPING_A 6d0
#define MAX_ATOMS_PER_BLOCK 6
