name: Deploy Documentation
on:
  workflow_call:
permissions:
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning
      - name: Build documentation
        run: make build_doc VIRTUAL_ENV=none
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: doc/build
      - uses: actions/deploy-pages@v4
