name: Deploy Documentation
on:
  workflow_call:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          repository: libmbd/libmbd
          fetch-depth: 0
      - uses: actions/setup-python@v6
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning
      - name: Build documentation
        run: make build_doc VIRTUAL_ENV=none
      - name: Set custom domain
        run: echo libmbd.nablapsi.science > doc/build/CNAME
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: doc/build
      - uses: actions/deploy-pages@v5
