name: Documentation
on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.repository == 'libmbd/libmbd'
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
      - name: Install Poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning
      - name: Build documentation
        run: make build_doc VIRTUAL_ENV=none
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: docs
          path: doc/build
